enum Type1 {
    IMM,
    DIR,
    EXT,
    IND,
}

enum Type2 {
    DIR,
    EXT,
    IND,
}

enum Typelea {
    DIR,
    EXT,
    IND,
}

enum Typebr {

}

enum Typepspl {

}

enum Typecc {

}

enum Typesc {

}

enum Typext {

}

enum Typemisc {

}

enum Instruction {
    ABX(Typemisc),
    ADCA(Type1),
    ADCB(Type1),
    ADDA(Type1),
    ADDB(Type1),
    ADDD(Type1),
    ANDA(Type1),
    ANDB(Type1),
    ANDCC(Typecc),
    ASLA(Typemisc),
    ASLB(Typemisc),
    ASL(Type2),
    ASRA(Typemisc),
    ASRB(Typemisc),
    ASR(Type2),
    BCC(Typebr),
    BCS(Typebr),
    BEQ(Typebr),
    BGE(Typebr),
    BGT(Typebr),
    BHI(Typebr),
    BHS(Typebr),
    BITA(Type1),
    BITB(Type1),
    BLE(Typebr),
    BLO(Typebr),
    BLS(Typebr),
    BLT(Typebr),
    BMI(Typebr),
    BNE(Typebr),
    BPL(Typebr),
    BRA(Typebr),
    BRN(Typebr),
    BSR(Typebr),
    BVC(Typebr),
    BVS(Typebr),
    CLC(Typesc),
    CLF(Typesc),
    CLI(Typesc),
    CLIF(Typesc),
    CLRA(Typemisc),
    CLRB(Typemisc),
    CLR(Type2),
    CLV(Typesc),
    CMPA(Type1),
    CMPB(Type1),
    CMPD(Type1),
    CMPS(Type1),
    CMPU(Type1),
    CMPX(Type1),
    CMPY(Type1),
    COMA(Typemisc),
    COMB(Typemisc),
    COM(Type2),
    CWAI(Typecc),
    DAA(Typemisc),
    DECA(Typemisc),
    DECB(Typemisc),
    DEC(Type2),
    EORA(Type1),
    EORB(Type1),
    EXG(Typext),
    INCA(Typemisc),
    INCB(Typemisc),
    INC(Type2),
    JMP(Type2),
    JSR(Type1),
    LBCC(Typebr),
    LBCS(Typebr),
    LBEQ(Typebr),
    LBGE(Typebr),
    LBGT(Typebr),
    LBHI(Typebr),
    LBHS(Typebr),
    LBLE(Typebr),
    LBLO(Typebr),
    LBLS(Typebr),
    LBLT(Typebr),
    LBMI(Typebr),
    LBNE(Typebr),
    LBPL(Typebr),
    LBRA(Typebr),
    LBRN(Typebr),
    LBSR(Typebr),
    LBVC(Typebr),
    LBVS(Typebr),
    LDA(Type1),
    LDB(Type1),
    LDD(Type1),
    LDS(Type1),
    LDU(Type1),
    LDX(Type1),
    LDY(Type1),
    LEAS(Typelea),
    LEAU(Typelea),
    LEAX(Typelea),
    LEAY(Typelea),
    LSLA(Typemisc),
    LSLB(Typemisc),
    LSL(Type2),
    LSRA(Typemisc),
    LSRB(Typemisc),
    LSR(Type2),
    MUL(Typemisc),
    NEGA(Typemisc),
    NEGB(Typemisc),
    NEG(Type2),
    NOP(Typemisc),
    ORA(Type1),
    ORB(Type1),
    ORCC(Typecc),
    PSHU(Typepspl),
    PSHS(Typepspl),
    PULU(Typepspl),
    PULS(Typepspl),
    ROLA(Typemisc),
    ROLB(Typemisc),
    ROL(Type2),
    RORA(Typemisc),
    RORB(Typemisc),
    ROR(Type2),
    RTI(Typemisc),
    RTS(Typemisc),
    SBCA(Type1),
    SBCB(Type1),
    SBCC(Typebr),
    SBCS(Typebr),
    SBEQ(Typebr),
    SBLT(Typebr),
    SBLE(Typebr),
    SBGT(Typebr),
    SBGE(Typebr),
    SLO(Typebr),
    SLS(Typebr),
    SLT(Typebr),
    SMI(Typebr),
    SNE(Typebr),
    SPL(Typebr),
    SRA(Typebr),
    SRN(Typebr),
    SSR(Typebr),
    SVC(Typebr),
    SBVS(Typebr),
    SEC(Typesc),
    SEF(Typesc),
    SEI(Typesc),
    SEIF(Typesc),
    SEV(Typesc),
    SEX(Typemisc),
    STA(Type1),
    STB(Type1),
    STD(Type1),
    STS(Type1),
    STU(Type1),
    STX(Type1),
    STY(Type1),
    SUBA(Type1),
    SUBB(Type1),
    SUBD(Type1),
    SWI(Typemisc),
    SWI2(Typemisc),
    SWI3(Typemisc),
    SYNC(Typemisc),
    TFR(Typext),
    TSTA(Typemisc),
    TSTB(Typemisc),
    TST(Type2)
}

fn main() {
    println!("Hello, world!");
}
