enum Register {
    A,
    B,
    D,
    X,
    Y,
    U,
    S,
    PC,
    DP
}

enum Type0 {
}

enum Type1 {
    IMM,
    DIR,
    EXT,
    IND,
}

enum Type2 {
    DIR,
    EXT,
    IND,
}

enum Typelea {
    DIR,
    EXT,
    IND,
}

enum Typebr {

}

enum Typepspl {

}

enum Typecc {

}

enum Typesc {

}

enum Typext {

}

enum Instruction {
    ABX(Type0),
    ADCA(Type1),
    ADCB(Type1),
    ADDA(Type1),
    ADDB(Type1),
    ADDD(Type1),
    ANDA(Type1),
    ANDB(Type1),
    ANDCC(Typecc),
    ASLA(Type0),
    ASLB(Type0),
    ASL(Type2),
    ASRA(Type0),
    ASRB(Type0),
    ASR(Type2),
    BCC(Typebr),
    BCS(Typebr),
    BEQ(Typebr),
    BGE(Typebr),
    BGT(Typebr),
    BHI(Typebr),
    BHS(Typebr),
    BITA(Type1),
    BITB(Type1),
    BLE(Typebr),
    BLO(Typebr),
    BLS(Typebr),
    BLT(Typebr),
    BMI(Typebr),
    BNE(Typebr),
    BPL(Typebr),
    BRA(Typebr),
    BRN(Typebr),
    BSR(Typebr),
    BVC(Typebr),
    BVS(Typebr),
    CLC(Typesc),
    CLF(Typesc),
    CLI(Typesc),
    CLIF(Typesc),
    CLRA(Type0),
    CLRB(Type0),
    CLR(Type2),
    CLV(Typesc),
    CMPA(Type1),
    CMPB(Type1),
    CMPD(Type1),
    CMPS(Type1),
    CMPU(Type1),
    CMPX(Type1),
    CMPY(Type1),
    COMA(Type0),
    COMB(Type0),
    COM(Type2),
    CWAI(Typecc),
    DAA(Type0),
    DECA(Type0),
    DECB(Type0),
    DEC(Type2),
    EORA(Type1),
    EORB(Type1),
    EXG(Typext),
    INCA(Type0),
    INCB(Type0),
    INC(Type2),
    JMP(Type2),
    JSR(Type1),
    LBCC(Typebr),
    LBCS(Typebr),
    LBEQ(Typebr),
    LBGE(Typebr),
    LBGT(Typebr),
    LBHI(Typebr),
    LBHS(Typebr),
    LBLE(Typebr),
    LBLO(Typebr),
    LBLS(Typebr),
    LBLT(Typebr),
    LBMI(Typebr),
    LBNE(Typebr),
    LBPL(Typebr),
    LBRA(Typebr),
    LBRN(Typebr),
    LBSR(Typebr),
    LBVC(Typebr),
    LBVS(Typebr),
    LDA(Type1),
    LDB(Type1),
    LDD(Type1),
    LDS(Type1),
    LDU(Type1),
    LDX(Type1),
    LDY(Type1),
    LEAS(Typelea),
    LEAU(Typelea),
    LEAX(Typelea),
    LEAY(Typelea),
    LSLA(Type0),
    LSLB(Type0),
    LSL(Type2),
    LSRA(Type0),
    LSRB(Type0),
    LSR(Type2),
    MUL(Type0),
    NEGA(Type0),
    NEGB(Type0),
    NEG(Type2),
    NOP(Type0),
    ORA(Type1),
    ORB(Type1),
    ORCC(Typecc),
    PSHU(Typepspl),
    PSHS(Typepspl),
    PULU(Typepspl),
    PULS(Typepspl),
    ROLA(Type0),
    ROLB(Type0),
    ROL(Type2),
    RORA(Type0),
    RORB(Type0),
    ROR(Type2),
    RTI(Type0),
    RTS(Type0),
    SBCA(Type1),
    SBCB(Type1),
    SBCC(Typebr),
    SBCS(Typebr),
    SBEQ(Typebr),
    SBLT(Typebr),
    SBLE(Typebr),
    SBGT(Typebr),
    SBGE(Typebr),
    SLO(Typebr),
    SLS(Typebr),
    SLT(Typebr),
    SMI(Typebr),
    SNE(Typebr),
    SPL(Typebr),
    SRA(Typebr),
    SRN(Typebr),
    SSR(Typebr),
    SVC(Typebr),
    SBVS(Typebr),
    SEC(Typesc),
    SEF(Typesc),
    SEI(Typesc),
    SEIF(Typesc),
    SEV(Typesc),
    SEX(Type0),
    STA(Type1),
    STB(Type1),
    STD(Type1),
    STS(Type1),
    STU(Type1),
    STX(Type1),
    STY(Type1),
    SUBA(Type1),
    SUBB(Type1),
    SUBD(Type1),
    SWI(Type0),
    SWI2(Type0),
    SWI3(Type0),
    SYNC(Type0),
    TFR(Typext),
    TSTA(Type0),
    TSTB(Type0),
    TST(Type2)
}

fn main() {
    println!("Hello, world!");
}
